# Generated by Django 3.1.3 on 2020-11-23 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_chats_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='delivered_to',
        ),
        migrations.AddField(
            model_name='chats',
            name='delivered_to',
            field=models.ManyToManyField(blank=True, related_name='chat_delivered_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chats',
            name='seen_by',
        ),
        migrations.AddField(
            model_name='chats',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='chat_seen_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
