# Generated by Django 3.1.3 on 2020-11-24 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
